name: admiral_tablet_a
description: Tablet A — نظام بيع الكباش (مرحلة الشراء)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  provider: ^6.1.2
  uuid: ^4.5.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  generate: true
